### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by ynrng** [pakisha/customGallery#1]
Hi. First, thanks for the article from medium.
I wonder did you encounter any crashes caused by memory issues using this solution? 
For example if I have thousands of pictures in photo library, I will definitely get a crash. Any ideas on how to solve that?

**Comment by ynrng** [comment]
Ok, I find out maybe it's caused by swift ui list .
Anyway, a better solution will be using PHCachingImageManager instead of PHImageManager.

**Comment by pakisha** [comment]
@sugaE Hey, I didn't have those problems. I haven't tested it with swiftui, so I don't know what to expect. And thanks for the tip about PHCachingImageManager.
